export function generateCaseRef(): string {
  const year = new Date().getFullYear();
  const num  = Math.floor(10000 + Math.random() * 90000);
  return `R4H-${year}-${num}`;
}

export const UGANDA_DISTRICTS: Record<string, string[]> = {
  Kampala:        ["Kampala Central","Kawempe","Makindye","Nakawa","Rubaga"],
  Wakiso:         ["Entebbe","Kira","Makindye-Ssabagabo","Nansana","Wakiso","Busiro North","Busiro South","Katabi"],
  Mukono:         ["Mukono","Goma","Koome","Kyampisi","Ntenjeru","Nakifuma","Nama"],
  Buikwe:         ["Buikwe","Najja","Ngogwe","Nkokonjeru","Ssi-Bukunja"],
  Buvuma:         ["Buvuma","Busamuzi","Lugala"],
  Gomba:          ["Gomba East","Gomba West","Kabulasoke","Maddu"],
  Kalangala:      ["Bufumira","Bujumba","Kyamuswa","Mugoye"],
  Kalungu:        ["Bukulula","Kalungu East","Kalungu West","Lwabenge"],
  Kyankwanzi:     ["Butemba","Gayaza","Kikyusa","Lwamata","Nkooko"],
  Luweero:        ["Bamunanika","Butuntumula","Katikamu","Kikyusa","Luwero","Makulubita","Zirobwe"],
  Lwengo:         ["Kabuuma","Kalisizo","Lwengo","Malongo","Ndagwe"],
  Lyantonde:      ["Lyantonde","Lyamukatwe","Kasagama","Kaliiro"],
  Masaka:         ["Masaka","Buwunga","Kimanya-Kabonera","Nyendo-Mukungwe","Bukakata","Kosiya","Kyanamukaaka"],
  Mityana:        ["Busimbi","Butebo","Kalangaalo","Mityana","Muwanga","Bulera"],
  Mpigi:          ["Buwama","Kalungu","Lunguju","Mpigi","Muduuma"],
  Mubende:        ["Butoloogo","Kigando","Kitenga","Madudu","Mubende","Munyama","Kasambya"],
  Nakaseke:       ["Butalangu","Kalasa-Namukozi","Kasangombe","Kiwoko","Nakaseke","Ngoma"],
  Nakasongola:    ["Budyebo","Kalongo","Lwampanga","Nakasongola","Nabiswera","Wabinyonyi"],
  Rakai:          ["Byakabanda","Kakuuto","Kasasa","Kibanda","Kimuli","Kooki","Kyebe","Lwamaggwa","Lwanda","Rakai"],
  Sembabule:      ["Lwebitakuli","Mateete","Mijwala","Sembabule","Lwemiyaga"],
  Butebo:         ["Binyiny","Butebo","Naboa"],
  Jinja:          ["Jinja","Bugembe","Kakira","Mpumudde","Walukuba","Buwenge","Mafubira"],
  Bugiri:         ["Bugiri","Budhaya","Budiope","Bulesa","Buluguyi","Butebo","Buthebo","Iwemba","Muterere","Nabukalu"],
  Bugweri:        ["Bugweri","Bukooli North","Bukooli South","Bukooli Central"],
  Busia:          ["Busia","Buteba","Dabani","Lunyo","Masaba","Majanji","Nambale","Sikuda","Bulumbi"],
  Buyende:        ["Buyende","Kidera","Nkondo","Nsinze","Kagulu"],
  Iganga:         ["Iganga","Bukanga","Buyanga","Idudi","Ivukula","Makuutu","Nawandala","Muiganyira"],
  Kaliro:         ["Buyende","Kaliro","Namwiwa","Nawaikoke","Tirinyi"],
  Kamuli:         ["Bugulumbya","Butansi","Kamuli","Kidera","Kitayunjwa","Nabwigulu","Namasagali","Nawanyago","Wankole"],
  Kapchorwa:      ["Kapchorwa","Bukwo","Chema","Kaptanya","Sundet","Tegeres","Tingey"],
  Katakwi:        ["Katakwi","Kapujan","Ngariam","Nwoya","Ongongoja","Toroma","Usuk"],
  Kibuku:         ["Kasasira","Kibuku","Tirinyi","Kagumu","Kadama"],
  Kumi:           ["Kumi","Atutur","Kanyum","Ngora","Ongino","Mukongoro"],
  Luuka:          ["Buluutu","Ikumbya","Luuka","Waibale"],
  Manafwa:        ["Bubulo","Butebo","Lwakhakha","Manafwa","Namisuni","Bumbo"],
  Mayuge:         ["Baitambogwe","Budiope","Imanyiro","Kigandalo","Majuge","Malongo","Wairasa"],
  Mbale:          ["Mbale","Bungokho","Bufumbo","Busiu","Wanale","Bungokho-Mutoto","Nawangoma","Nakaloke"],
  Namayingo:      ["Bukooli Central","Bukooli North","Namayingo","Sigulu"],
  Namisindwa:     ["Bubulo East","Bubulo West","Namisindwa","Magale"],
  Namutumba:      ["Bulange","Magada","Namutumba","Nsinze","Butebo"],
  Ngora:          ["Kapir","Kobwin","Ngora","Mukongoro"],
  Pallisa:        ["Butebo","Gogonyo","Kamuge","Kibale","Pallisa","Petete","Butebo"],
  Serere:         ["Bugondo","Kadungulu","Olio","Pingire","Serere"],
  Sironko:        ["Bukhulo","Bumasifwa","Buwalasi","Buyobo","Sironko","Sironko Town","Butandiga"],
  Soroti:         ["Soroti","Arapai","Gweri","Kamuda","Tubur","Katine","Asuret"],
  Tororo:         ["Tororo","Kirewa","Molo","Mukuju","Paya","Mulanda","Nagongera","Osukuru","Rubongi","Kwapa"],
  Abim:           ["Abim","Alerek","Karenga","Labwor","Nyakwae"],
  Adjumani:       ["Adjumani","Adropi","Dzaipi","Itirikwa","Lawibu","Ofua","Pakele","Pagirinya"],
  Agago:          ["Agago","Kalongo","Lapono","Lamiyo","Paimol","Patongo","Wol"],
  Alebtong:       ["Abako","Alebtong","Alito","Amolatar","Omoro"],
  Amolatar:       ["Amolatar","Arwot Miro","Etam","Muntu","Namasale"],
  Amudat:         ["Amudat","Loroo","Morulem"],
  Amuria:         ["Amuria","Abarilela","Acowa","Kapelebyong","Morungatuny","Wera"],
  Amuru:          ["Amuru","Atiak","Lamogi","Pabbo","Purongo"],
  Apac:           ["Apac","Abongomola","Aduku","Akokoro","Chegere","Inomo","Mogo","Nambieso","Nkoko","Teboke"],
  Arua:           ["Arua","Ayivu","Ogoko","Pajulu","Vurra","Dadamu","Logiri","Manibe","Oluko","Rigbo","Adumi"],
  Dokolo:         ["Dokolo","Adok","Batta","Kangai","Kwera","Lira Kato","Okwongodul"],
  Gulu:           ["Gulu","Awach","Koro","Lacor","Patiko","Lalogi","Layibi","Odek","Ongako","Paicho","Palaro","Unyama"],
  Kaabong:        ["Kaabong","Dodoth East","Dodoth West","Karenga","Lolelia","Loyoro","Napak","Sidok","Timu"],
  Kitgum:         ["Kitgum","Agoro","Akwang","Chua East","Chua West","Labongo Akwang","Labongo Amida","Labongo Layamo","Lokung","Orom","Omiya Anyima","Palabek Gem","Palabek Ogili","Palabek Kal","Pager","Potika","Namokora"],
  Koboko:         ["Koboko","Dranya","Kuluba","Ludara","Midia"],
  Kole:           ["Aboke","Akalo","Alito","Bala","Kole","Okidi North","Okidi South","Orumo"],
  Kotido:         ["Kotido","Jimos","Kacheri","Kotido","Nakapiripirit","Panyangara"],
  Kwania:         ["Akokoro","Chegere","Inomo","Kwania","Nambieso"],
  Lamwo:          ["Agoro","Lamwo","Madi-Okollo","Madi Opei","Palabek Gem","Palabek Ogili","Potika"],
  Lira:           ["Lira","Adekokwok","Agweng","Amach","Aromo","Barr","Jerukamonye","Ogur","Ojwina"],
  "Madi-Okollo":  ["Madi-Okollo","Ediofe","Omugo","Paidha","Nyapea"],
  Maracha:        ["Maracha","Oleba","Oluffe","Yivu"],
  Moroto:         ["Moroto","Katikekile","Nadunget","Rupe","Tapac"],
  Moyo:           ["Moyo","Dufile","Itula","Lefori","Metu"],
  Napak:          ["Iriiri","Lopeei","Lotome","Napak","Ngoleriet"],
  Nebbi:          ["Nebbi","Akworo","Alwi","Jonam","Kucwiny","Nyagak Nena","Panyimur","Padwari"],
  Nwoya:          ["Anaka","Koch Goma","Nwoya","Purongo","Tee-Okot"],
  Obongi:         ["Obongi","Gimara","Palorinya"],
  Omoro:          ["Bobi","Lalogi","Odek","Omoro","Ongako"],
  Otuke:          ["Adwari","Okwongodul","Olilim","Otuke"],
  Oyam:           ["Aber","Aleka","Apac","Iceme","Minakulu","Ngai","Otwal","Oyam"],
  Pader:          ["Atanga","Awere","Lapono","Ogom","Pader","Puranga"],
  Pakwach:        ["Pakwach","Nwoya","Panyimur","Warr"],
  Terego:         ["Terego","Odupi","Ofua","Terego"],
  Yumbe:          ["Yumbe","Apo","Drajini","Kerwa","Kei","Kululu","Lodonga","Nari","Odravu","Romogi"],
  Zombo:          ["Zombo","Atyak","Jangokoro","Nyapea","Paidha"],
  Buliisa:        ["Biiso","Buliisa","Butiaba","Kigwera","Ngwedo"],
  Bundibugyo:     ["Bubandi","Bundibugyo","Busaru","Butebo","Harugale","Ntoroko","Nyahuka","Sindila"],
  Bushenyi:       ["Bushenyi-Ishaka","Igara East","Igara West","Kakanju","Kyabugimbi","Kyeijonjo","Masha","Rubirizi","Ryeru"],
  Buhweju:        ["Buhweju","Burara","Kagongi","Nyabubare"],
  Bunyangabu:     ["Bunyangabu","Kijura","Kisomoro","Kyebambe"],
  FortPortal:     ["Fort Portal","Bukuku","Busoro","Bunyangabu","Kijura","Rwimi"],
  Hoima:          ["Hoima","Buhimba","Bugahya","Kigorobya","Kitoba","Buhanika","Kabwoya","Kiziranfumbi","Kyabigambire","Kyangwali"],
  Ibanda:         ["Ibanda","Igorora","Ishongororo","Kagongo","Kikyenkye","Nyamarebe","Rugando"],
  Isingiro:       ["Birere","Endiinzi","Isingiro","Kabuyanda","Karera","Kikagate","Mbaare","Ngarama","Nyakitunda","Rugaaga","Ruborogota","Rushasha","Rwanyamahembe"],
  Kabale:         ["Kabale","Bufundi","Ikumba","Kaharo","Rubanda","Bukinda","Butanda","Bwambara","Kamuganguzi","Maziba","Muko","Ndorwa East","Ndorwa West","Rubanda"],
  Kabarole:       ["Buheesi","Bukuuku","Busoro","Fort Portal","Kabarole","Kasenda","Kateete","Kibale","Kibiito","Kiko","Rwimi","Ruteete"],
  Kagadi:         ["Kagadi","Bwikara","Buyanja","Kyaterekera","Nabbale","Nkondo","Rugashari"],
  Kakumiro:       ["Bugangaizi East","Bugangaizi West","Kakumiro","Kitagwenda","Luwunga","Mpasaana"],
  Kamwenge:       ["Buhara","Kamwenge","Kibale","Kicwamba","Kihuura","Nkoma","Nkoma","Rwenjaza"],
  Kanungu:        ["Butogota","Kayonza","Kihihi","Kirima","Mpungu","Mugyera","Rutenga","Kinkiizi East","Kinkiizi West"],
  Kasese:         ["Bugoye","Busongora North","Busongora South","Bwera","Ihandiro","Isango","Karusandara","Kasese","Katwe-Kabatoro","Kilembe","Kisinga","Lake Katwe","Maliba","Munkunyu","Muhokya","Rukoki","Rugendabara","Nyakiyumbu"],
  Kibaale:        ["Buyanja","Bwamba","Kagadi","Kabamba","Kakindo","Kibaale","Kikwaya","Kimisi","Kyaterekera","Mpeefu"],
  Kiruhura:       ["Buremba","Igorora","Kazo","Kiruhura","Ntuusi","Rwanyamahembe","Sanga"],
  Kiryandongo:    ["Bweyale","Kibanda","Kiryandongo","Masindi Port","Mutunda"],
  Kisoro:         ["Bukimbiri","Busanza","Chahi","Kirundo","Kisoro","Muramba","Nyarubuye","Nyundo","Rubuguri","Rushaga"],
  Kyegegwa:       ["Hapuuyo","Kyegegwa","Kyenjojo","Mpara","Ruyonza"],
  Kyenjojo:       ["Bufunjo","Butebo","Bwamba","Kabwoya","Kasule","Kyenjojo","Mwenge North","Mwenge South","Mwenge West","Nyabuharwa"],
  Masindi:        ["Budongo","Bujenje","Buruli","Kigumba","Kiryandongo","Masindi","Masindi Port","Miirya","Pakanyi"],
  Mbarara:        ["Mbarara","Biharwe","Kakoba","Kamukuzi","Nyamitanga","Bubaare","Bugamba","Bwizibwera","Kakiika","Kagongi","Kashari North","Kashari South","Kyare","Mwizi","Rubaya","Rwanyamahembe"],
  Mitooma:        ["Bitereko","Kashenshero","Kibatsi","Mitooma","Mutara","Ruhinda"],
  Ntoroko:        ["Butebo","Karugutu","Kibuku","Ntoroko"],
  Ntungamo:       ["Itojo","Ihunga","Kayonza","Kibatsi","Kitwe","Ntungamo","Nyabihoko","Nyakyera","Ruhaama","Ruhaama East","Rukoni East","Rukoni West","Rwashamaire"],
  Rubanda:        ["Bufundi","Ikumba","Kaharo","Muko","Rubanda","Bubare"],
  Rubirizi:       ["Bunyaruguru","Katerera","Kibale","Kichwamba","Rubirizi"],
  Rukiga:         ["Kamwezi","Nyarubuye","Rubanda","Rukiga"],
  Rukungiri:      ["Buyanja","Buyombe","Kebisoni","Kagunga","Nyakishenyi","Nyarushanje","Ruhinda","Rukungiri","Rubabo"],
  Sheema:         ["Kitagata","Masheruka","Nyabubare","Sheema North","Sheema South"],
};

export const AGE_RANGES       = ["Below 18","18–24","25–35","36–45","Above 45","Prefer not to say"];
export const GENDER_OPTIONS    = ["Woman","Man","Self-describe","Prefer not to say"];
export const DISABILITY_OPTIONS = ["None","Physical disability","Visual impairment","Hearing impairment","Psychosocial disability","Intellectual disability","Chronic illness","Other","Prefer not to say"];
export const VIOLENCE_TYPES    = ["Physical","Sexual","Emotional/Psychological","Economic","Digital/Online Abuse","Environmental / Climate-related","Other"];
export const DIGITAL_ABUSE_TYPES = ["Non-consensual images","Online stalking","Impersonation","Account takeover","Harassment","Doxxing","Other"];
export const PERPETRATOR_OPTIONS = ["Intimate partner","Family member","Community member","Employer","State actor","Religious/cultural leader","Unknown","Online-only / anonymous","Other"];
export const CONTRIBUTING_FACTORS = ["Gender inequality","Economic dependency","Harmful norms","Weak justice systems","Climate/environmental stress","Other"];
export const REPORTED_TO_OPTIONS  = ["Local leader","Police","Health facility","NGO/CBO","Safe shelter","Other"];
export const SUPPORT_SERVICES     = ["Medical","Psychosocial","Legal aid","Safe shelter","Livelihood support","None","Other"];
export const PRIORITY_SUPPORT     = ["Legal","Psychosocial","Medical","Safe shelter","Financial/livelihood","Advocacy","Other"];
export const CONTACT_METHODS      = ["Phone","Email","WhatsApp"];
export const RISK_ASSESSMENT_OPTIONS = ["Ongoing danger","Medical emergency","Child survivor","State actor involved","High digital risk"];
